version: '3.8'

services:
  backend:
    build: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: mysql:8.4.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: assignment
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
