version: '3.8'

services:
  backend:
    build: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  db:
    image: mysql:8.4.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: assignment
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  db_test:
    image: mysql:8.4.4
    container_name: mysql-db-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: assignment_test
    ports:
      - "33060:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
  mysql_data_test:
  redis_data:
