// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "backend-developer-assignment/app/models"

	mock "github.com/stretchr/testify/mock"

	types "backend-developer-assignment/pkg/types"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

// CreateAccountWithDetails provides a mock function with given fields: accountWithDetails
func (_m *AccountService) CreateAccountWithDetails(accountWithDetails *models.AccountWithDetails) error {
	ret := _m.Called(accountWithDetails)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccountWithDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AccountWithDetails) error); ok {
		r0 = rf(accountWithDetails)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccount provides a mock function with given fields: accountID
func (_m *AccountService) DeleteAccount(accountID string) error {
	ret := _m.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepositToAccount provides a mock function with given fields: accountID, amount
func (_m *AccountService) DepositToAccount(accountID string, amount float64) (float64, error) {
	ret := _m.Called(accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for DepositToAccount")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (float64, error)); ok {
		return rf(accountID, amount)
	}
	if rf, ok := ret.Get(0).(func(string, float64) float64); ok {
		r0 = rf(accountID, amount)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(accountID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByID provides a mock function with given fields: accountID
func (_m *AccountService) GetAccountByID(accountID string) (*models.Account, error) {
	ret := _m.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Account, error)); ok {
		return rf(accountID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Account); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountWithDetailByID provides a mock function with given fields: accountID
func (_m *AccountService) GetAccountWithDetailByID(accountID string) (*models.AccountWithDetails, error) {
	ret := _m.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountWithDetailByID")
	}

	var r0 *models.AccountWithDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.AccountWithDetails, error)); ok {
		return rf(accountID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.AccountWithDetails); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccountWithDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountsByUserID provides a mock function with given fields: userID
func (_m *AccountService) GetAccountsByUserID(userID string) ([]*models.Account, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsByUserID")
	}

	var r0 []*models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Account, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Account); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountsWithDetailByUserID provides a mock function with given fields: userID
func (_m *AccountService) GetAccountsWithDetailByUserID(userID string) ([]*models.AccountWithDetails, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsWithDetailByUserID")
	}

	var r0 []*models.AccountWithDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.AccountWithDetails, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.AccountWithDetails); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AccountWithDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetMainAccount provides a mock function with given fields: account
func (_m *AccountService) SetMainAccount(account *models.Account) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for SetMainAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferBetweenAccounts provides a mock function with given fields: fromAccountID, toAccountID, amount
func (_m *AccountService) TransferBetweenAccounts(fromAccountID string, toAccountID string, amount float64) (*types.TransferResult, error) {
	ret := _m.Called(fromAccountID, toAccountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for TransferBetweenAccounts")
	}

	var r0 *types.TransferResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, float64) (*types.TransferResult, error)); ok {
		return rf(fromAccountID, toAccountID, amount)
	}
	if rf, ok := ret.Get(0).(func(string, string, float64) *types.TransferResult); ok {
		r0 = rf(fromAccountID, toAccountID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.TransferResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, float64) error); ok {
		r1 = rf(fromAccountID, toAccountID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAccount provides a mock function with given fields: account
func (_m *AccountService) UpdateAccount(account *models.AccountWithDetails) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AccountWithDetails) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawFromAccount provides a mock function with given fields: accountID, amount
func (_m *AccountService) WithdrawFromAccount(accountID string, amount float64) (float64, error) {
	ret := _m.Called(accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawFromAccount")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (float64, error)); ok {
		return rf(accountID, amount)
	}
	if rf, ok := ret.Get(0).(func(string, float64) float64); ok {
		r0 = rf(accountID, amount)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(accountID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
