// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "backend-developer-assignment/app/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: transaction
func (_m *TransactionService) CreateTransaction(transaction *models.Transaction) error {
	ret := _m.Called(transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTransactionByID provides a mock function with given fields: id
func (_m *TransactionService) GetTransactionByID(id string) (*models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByUserID provides a mock function with given fields: userID, page
func (_m *TransactionService) GetTransactionsByUserID(userID string, page int) ([]*models.Transaction, int, error) {
	ret := _m.Called(userID, page)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByUserID")
	}

	var r0 []*models.Transaction
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int) ([]*models.Transaction, int, error)); ok {
		return rf(userID, page)
	}
	if rf, ok := ret.Get(0).(func(string, int) []*models.Transaction); ok {
		r0 = rf(userID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) int); ok {
		r1 = rf(userID, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, int) error); ok {
		r2 = rf(userID, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
