// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	repositories "backend-developer-assignment/app/repositories"

	mock "github.com/stretchr/testify/mock"
)

// TxProvider is an autogenerated mock type for the TxProvider type
type TxProvider struct {
	mock.Mock
}

// Transact provides a mock function with given fields: txFunc
func (_m *TxProvider) Transact(txFunc func(repositories.Adapters) error) error {
	ret := _m.Called(txFunc)

	if len(ret) == 0 {
		panic("no return value specified for Transact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(repositories.Adapters) error) error); ok {
		r0 = rf(txFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTxProvider creates a new instance of TxProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxProvider {
	mock := &TxProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
