ALTER TABLE transaction
ADD COLUMN amount INTEGER NOT NULL DEFAULT 0;

ADD COLUMN transaction_type VARCHAR(255) NOT NULL DEFAULT 'deposit';

ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;